"""Adult general reference defaults; declarative catalogue may exceed 300 lines."""

from decimal import Decimal
from typing import cast

from care_suriname.resources.laboratory_reference.specs import (
    ReferenceApplicability,
    ReferenceBound,
    ReferenceCatalogueEntry,
    ReferenceSource,
    SexBasis,
    Specimen,
    TextbookReferenceRule,
)

UCUM = "http://unitsofmeasure.org"
ACCESSED = "2026-09-20"


def _source(id_: str, publisher: str, title: str, url: str, *limits: str):
    return ReferenceSource(id_, publisher, title, url, ACCESSED, limits)


TEXTBOOK_REFERENCE_SOURCES = {
    source.id: source
    for source in (
        _source(
            "ucsf-cbc-2024",
            "UCSF Health",
            "CBC blood test",
            "https://www.ucsfhealth.org/care/medical-tests/cbc-blood-test",
            "General adult examples; altitude and local laboratory intervals may differ.",
            "Page cites Henry's Clinical Diagnosis and Management by Laboratory Methods, 24th ed.",
            "The source uses generic blood wording; governed CBC applicability accepts an explicitly recorded whole-blood specimen as the narrower collection form.",
        ),
        _source(
            "ucsf-cmp-2025",
            "UCSF Health",
            "Comprehensive metabolic panel",
            "https://www.ucsfhealth.org/care/medical-tests/comprehensive-metabolic-panel",
            "General blood-test examples; local specimen and analytical methods may differ.",
            "The page instructs fasting for at least eight hours.",
            "The page says blood sample; serum/plasma specificity here comes from each exact LOINC definition, not the range page.",
        ),
        _source(
            "worcs-fbc",
            "Worcestershire Acute Hospitals NHS Trust",
            "Full Blood Count",
            "https://www.worcsacute.nhs.uk/pathology-tests-a-to-z/full-blood-count/",
            "Adult EDTA whole-blood platelet interval; source attributes adult ranges to Pathology Harmony.",
        ),
        _source(
            "ouh-sodium-2025",
            "Oxford University Hospitals NHS Foundation Trust",
            "Sodium",
            "https://www.ouh.nhs.uk/biochemistry/tests/tests-catalogue/sodium/",
            "Adult serum; no special collection requirements; indirect diluted ion-selective electrode.",
        ),
        _source(
            "ouh-potassium-2024",
            "Oxford University Hospitals NHS Foundation Trust",
            "Potassium",
            "https://www.ouh.nhs.uk/biochemistry/tests/tests-catalogue/potassium/",
            "Adult serum; process within 24 hours; indirect diluted ion-selective electrode.",
        ),
        _source(
            "ouh-creatinine-2025",
            "Oxford University Hospitals NHS Foundation Trust",
            "Creatinine",
            "https://www.ouh.nhs.uk/biochemistry/tests/tests-catalogue/creatinine/",
            "Adult serum; no special collection requirements; enzymatic creatininase/sarcosine oxidase method.",
            "Published adult intervals apply to age over 18 and vary by sex; age, build and pregnancy affect creatinine.",
        ),
        _source(
            "ouh-chloride-2025",
            "Oxford University Hospitals NHS Foundation Trust",
            "Chloride",
            "https://www.ouh.nhs.uk/biochemistry/tests/tests-catalogue/chloride/",
            "Adult serum; no special collection requirements; indirect diluted ion-selective electrode.",
        ),
        _source(
            "ouh-bicarbonate-2025",
            "Oxford University Hospitals NHS Foundation Trust",
            "Bicarbonate",
            "https://www.ouh.nhs.uk/biochemistry/tests/tests-catalogue/bicarbonate/",
            "Adult serum; separate and analyse within four hours; enzymatic PEP carboxylase method.",
        ),
        _source(
            "pathology-harmony-adult-2011",
            "Pathology Harmony Group / Association for Laboratory Medicine",
            "Agreed Adult Clinical Biochemistry Reference Intervals",
            "https://labmed.org.uk/asset/EEA82309-7E93-417D-9B8991B0C65C52FB/",
            "Professional consensus intervals for harmonisable adult analytes with no clearly identifiable reason for inter-laboratory differences.",
            "The adult table publishes exact SI units but does not state specimen; serum/plasma applicability comes from the exact LOINC definition.",
            "General defaults may differ from the reporting laboratory's own interval.",
        ),
        _source(
            "murtagh-general-practice-9e-2025",
            "McGraw Hill Medical",
            "John Murtagh's General Practice Companion Handbook, 9th Edition — Laboratory Reference Values",
            "https://accessworldmed.mhmedical.com/content.aspx?bookid=3601&sectionid=300146270",
            "General adult SI reference table; the publisher states ranges may vary from laboratory to laboratory.",
            "The creatinine row does not state specimen; serum/plasma applicability comes from the exact LOINC definition.",
            "Creatinine varies with muscle mass and other patient factors; this is not a kidney-function diagnosis threshold.",
        ),
        _source(
            "ucsf-crp",
            "UCSF Health",
            "C-reactive protein",
            "https://www.ucsfhealth.org/care/medical-tests/c-reactive-protein",
            "Ordinary CRP, not hs-CRP; values vary with age, sex and population.",
        ),
        _source(
            "ucsf-esr",
            "UCSF Health",
            "ESR",
            "https://www.ucsfhealth.org/care/medical-tests/esr",
            "Westergren method only; upper limits are strict less-than thresholds.",
        ),
        _source(
            "ucsf-ggt-2025",
            "UCSF Health",
            "Gamma-glutamyl transferase blood test",
            "https://www.ucsfhealth.org/care/medical-tests/gamma-glutamyl-transferase-ggt-blood-test",
            "General adult interval; medicines and alcohol may affect results.",
        ),
        _source(
            "ucsf-magnesium-2025",
            "UCSF Health",
            "Magnesium blood test",
            "https://www.ucsfhealth.org/care/medical-tests/magnesium-blood-test",
            "Serum magnesium; laboratory intervals may differ.",
        ),
        _source(
            "ucsf-pt-2025",
            "UCSF Health",
            "Prothrombin time",
            "https://www.ucsfhealth.org/care/medical-tests/prothrombin-time-pt",
            "Applies only when the patient is not taking warfarin or another anticoagulant.",
        ),
        _source(
            "ucsf-ptt-2025",
            "UCSF Health",
            "Partial thromboplastin time",
            "https://www.ucsfhealth.org/care/medical-tests/partial-thromboplastin-time-ptt",
            "Applies only when the patient is not taking an anticoagulant.",
        ),
        _source(
            "mayo-phosphate-2026",
            "Mayo Clinic Laboratories",
            "Phosphorus (Inorganic), Serum",
            "https://www.mayocliniclabs.com/test-catalog/Overview/8408",
            "Published interval is mg/dL, not the configured mmol/L; no automatic conversion is used.",
            "Method is photometric and concentrations have a strong circadian rhythm.",
        ),
        _source(
            "mayo-psa-2026",
            "Mayo Clinic Laboratories",
            "Prostate-Specific Antigen Diagnostic, Serum",
            "https://www.mayocliniclabs.com/test-catalog/overview/9284",
            "Method-dependent serum immunoassay; age-specific 95th percentile limits are not diagnostic cutoffs.",
            "Recent prostate instrumentation can increase PSA.",
        ),
        _source(
            "abim-reference-ranges-2026",
            "American Board of Internal Medicine",
            "Laboratory Test Reference Ranges",
            "https://www.abim.org/media/e2wdwdqu/laboratory-reference-ranges.pdf",
            "January 2026 examination reference table; its PSA entry explicitly has no established reference range.",
            "ABIM states that laboratory values vary with methods and local laboratories.",
        ),
        _source(
            "ngsp-ifcc",
            "NGSP",
            "IFCC Standardization Overview",
            "https://ngsp.org/ifcc.asp",
            "Standardization and unit relationship only; it does not publish a normal reference interval.",
        ),
        _source(
            "nwl-hba1c-2025",
            "North West London Pathology",
            "Glycated haemoglobin (HbA1c)",
            "https://www.nwlpathology.nhs.uk/test/glycated-haemoglobin-hba1c/",
            "EDTA whole blood measured by IFCC-traceable ion-exchange chromatography.",
            "Not applicable in pregnancy, childhood, renal failure, anaemia, haemoglobinopathy, HIV, or abnormal red-cell turnover.",
            "Published reference interval is distinct from diagnostic cutoffs and treatment targets.",
        ),
        _source(
            "ouh-urea-2025",
            "Oxford University Hospitals",
            "Urea",
            "https://www.ouh.nhs.uk/biochemistry/tests/tests-catalogue/urea/",
            "Adult serum interval; spectrophotometric enzymatic urease/glutamate-dehydrogenase method.",
        ),
        _source(
            "olvg-hb",
            "OLVG Lab BV",
            "Hemoglobine (Hb)",
            "https://olvglab.nl/voor-zorgverleners/bepalingen-en-referentiewaarden/referentiewaarden/hematologie-volledig-bloedbeeld-hemoglobine-hb/",
            "EDTA whole-blood laboratory interval; not validated for another analyser or method.",
        ),
    )
}


def _bound(value: str, inclusive: bool = True) -> ReferenceBound:
    return ReferenceBound(Decimal(value), inclusive)


def _app(
    sex: str = "any",
    maximum_age: int | None = None,
    *required_context: str,
) -> ReferenceApplicability:
    return ReferenceApplicability(
        minimum_age_years=18,
        maximum_age_years=maximum_age,
        sex=cast(SexBasis, sex),
        required_context=required_context,
    )


def _rule(
    id_: str,
    loinc: str,
    title: str,
    unit: str | None,
    specimen: str,
    lower: str | None,
    upper: str | None,
    source: str,
    *,
    applicability: ReferenceApplicability | None = None,
    lower_inclusive: bool = True,
    upper_inclusive: bool = True,
    limitations: tuple[str, ...] = (),
    method: str = "unspecified",
) -> TextbookReferenceRule:
    if source == "ucsf-cmp-2025" and applicability is None:
        applicability = _app("any", None, "fasting_confirmed")
    return TextbookReferenceRule(
        id=id_,
        loinc=loinc,
        title=title,
        unit_system=UCUM if unit is not None else "",
        unit_code=unit,
        specimen=cast(Specimen, specimen),
        method=method,
        applicability=applicability or _app(),
        lower=_bound(lower, lower_inclusive) if lower is not None else None,
        upper=_bound(upper, upper_inclusive) if upper is not None else None,
        source_id=source,
        limitations=limitations,
    )


def _entry(
    loinc: str,
    title: str,
    unit: str | None,
    *rules,
    unavailable=None,
    provenance_sources=(),
    catalogue_version="general-academic-adult-v1",
):
    return ReferenceCatalogueEntry(
        loinc,
        title,
        UCUM if unit is not None else "",
        unit,
        rules,
        unavailable,
        provenance_sources,
        catalogue_version,
    )


_cbc = "ucsf-cbc-2024"
_cmp = "ucsf-cmp-2025"
_anticoagulant = ("Requires confirmed absence of anticoagulant treatment.",)

TEXTBOOK_REFERENCE_CATALOGUE = (
    _entry(
        "718-7",
        "Hemoglobine",
        "g/dL",
        _rule(
            "hb-gdl-male",
            "718-7",
            "Hemoglobine",
            "g/dL",
            "blood",
            "13",
            "18",
            _cbc,
            applicability=_app("male"),
        ),
        _rule(
            "hb-gdl-female",
            "718-7",
            "Hemoglobine",
            "g/dL",
            "blood",
            "12",
            "16",
            _cbc,
            applicability=_app("female"),
        ),
    ),
    _entry(
        "59260-0",
        "Hemoglobine",
        "mmol/L",
        _rule(
            "hb-mmol-male",
            "59260-0",
            "Hemoglobine",
            "mmol/L",
            "whole_blood",
            "8.5",
            "11",
            "olvg-hb",
            applicability=_app("male"),
        ),
        _rule(
            "hb-mmol-female",
            "59260-0",
            "Hemoglobine",
            "mmol/L",
            "whole_blood",
            "7.5",
            "10",
            "olvg-hb",
            applicability=_app("female"),
        ),
    ),
    _entry(
        "4544-3",
        "Hematocriet",
        "%",
        _rule(
            "hct-male",
            "4544-3",
            "Hematocriet",
            "%",
            "blood",
            "40",
            "55",
            _cbc,
            applicability=_app("male"),
        ),
        _rule(
            "hct-female",
            "4544-3",
            "Hematocriet",
            "%",
            "blood",
            "36",
            "48",
            _cbc,
            applicability=_app("female"),
        ),
    ),
    _entry(
        "789-8",
        "Erytrocyten",
        "10*6/uL",
        _rule(
            "rbc-male",
            "789-8",
            "Erytrocyten",
            "10*6/uL",
            "blood",
            "4.6",
            "6.2",
            _cbc,
            applicability=_app("male"),
        ),
        _rule(
            "rbc-female",
            "789-8",
            "Erytrocyten",
            "10*6/uL",
            "blood",
            "4.2",
            "5.4",
            _cbc,
            applicability=_app("female"),
        ),
    ),
    _entry(
        "6690-2",
        "Leukocyten",
        "10*9/L",
        _rule("wbc", "6690-2", "Leukocyten", "10*9/L", "blood", "4.5", "11", _cbc),
    ),
    _entry(
        "777-3",
        "Trombocyten",
        "10*9/L",
        _rule(
            "platelets",
            "777-3",
            "Trombocyten",
            "10*9/L",
            "whole_blood",
            "150",
            "400",
            "worcs-fbc",
        ),
    ),
    _entry(
        "787-2",
        "MCV",
        "fL",
        _rule("mcv", "787-2", "MCV", "fL", "blood", "80", "100", _cbc),
    ),
    _entry(
        "14682-9",
        "Creatinine",
        "umol/L",
        _rule(
            "creatinine-male",
            "14682-9",
            "Creatinine",
            "umol/L",
            "serum_or_plasma",
            "60",
            "120",
            "murtagh-general-practice-9e-2025",
            applicability=_app("male"),
        ),
        _rule(
            "creatinine-female",
            "14682-9",
            "Creatinine",
            "umol/L",
            "serum_or_plasma",
            "50",
            "110",
            "murtagh-general-practice-9e-2025",
            applicability=_app("female"),
        ),
        catalogue_version="general-academic-adult-v2",
    ),
    _entry(
        "22664-7",
        "Ureum",
        "mmol/L",
        _rule(
            "urea",
            "22664-7",
            "Ureum",
            "mmol/L",
            "serum_or_plasma",
            "2.5",
            "7.8",
            "pathology-harmony-adult-2011",
        ),
        catalogue_version="general-academic-adult-v2",
    ),
    _entry(
        "2951-2",
        "Natrium",
        "mmol/L",
        _rule(
            "sodium",
            "2951-2",
            "Natrium",
            "mmol/L",
            "serum_or_plasma",
            "133",
            "146",
            "pathology-harmony-adult-2011",
        ),
        catalogue_version="general-academic-adult-v2",
    ),
    _entry(
        "2823-3",
        "Kalium",
        "mmol/L",
        _rule(
            "potassium",
            "2823-3",
            "Kalium",
            "mmol/L",
            "serum_or_plasma",
            "3.5",
            "5.3",
            "pathology-harmony-adult-2011",
        ),
        catalogue_version="general-academic-adult-v2",
    ),
    _entry(
        "2075-0",
        "Chloride",
        "mmol/L",
        _rule(
            "chloride",
            "2075-0",
            "Chloride",
            "mmol/L",
            "serum_or_plasma",
            "95",
            "108",
            "pathology-harmony-adult-2011",
        ),
        catalogue_version="general-academic-adult-v2",
    ),
    _entry(
        "1963-8",
        "Bicarbonaat",
        "mmol/L",
        _rule(
            "bicarbonate",
            "1963-8",
            "Bicarbonaat",
            "mmol/L",
            "serum_or_plasma",
            "22",
            "29",
            "pathology-harmony-adult-2011",
        ),
        catalogue_version="general-academic-adult-v2",
    ),
    _entry(
        "1988-5",
        "CRP",
        "mg/L",
        _rule(
            "crp",
            "1988-5",
            "CRP",
            "mg/L",
            "serum_or_plasma",
            None,
            "3",
            "ucsf-crp",
            upper_inclusive=False,
        ),
    ),
    _entry(
        "4537-7",
        "BSE Westergren",
        "mm/h",
        _rule(
            "esr-male-under-50",
            "4537-7",
            "BSE Westergren",
            "mm/h",
            "whole_blood",
            None,
            "15",
            "ucsf-esr",
            applicability=_app("male", 49),
            upper_inclusive=False,
        ),
        _rule(
            "esr-male-over-50",
            "4537-7",
            "BSE Westergren",
            "mm/h",
            "whole_blood",
            None,
            "20",
            "ucsf-esr",
            applicability=ReferenceApplicability(51, None, "male"),
            upper_inclusive=False,
        ),
        _rule(
            "esr-female-under-50",
            "4537-7",
            "BSE Westergren",
            "mm/h",
            "whole_blood",
            None,
            "20",
            "ucsf-esr",
            applicability=_app("female", 49),
            upper_inclusive=False,
        ),
        _rule(
            "esr-female-over-50",
            "4537-7",
            "BSE Westergren",
            "mm/h",
            "whole_blood",
            None,
            "30",
            "ucsf-esr",
            applicability=ReferenceApplicability(51, None, "female"),
            upper_inclusive=False,
        ),
    ),
    _entry(
        "1742-6",
        "ALAT serum",
        "U/L",
        _rule("alt", "1742-6", "ALAT serum", "U/L", "serum_or_plasma", "4", "36", _cmp),
    ),
    _entry(
        "1920-8",
        "ASAT serum",
        "U/L",
        _rule("ast", "1920-8", "ASAT serum", "U/L", "serum_or_plasma", "8", "33", _cmp),
    ),
    _entry(
        "6768-6",
        "Alkalische fosfatase",
        "U/L",
        _rule(
            "alp",
            "6768-6",
            "Alkalische fosfatase",
            "U/L",
            "serum_or_plasma",
            "20",
            "130",
            _cmp,
        ),
    ),
    _entry(
        "2324-2",
        "Gamma-GT",
        "U/L",
        _rule("ggt", "2324-2", "Gamma-GT", "U/L", "serum", "5", "40", "ucsf-ggt-2025"),
    ),
    _entry(
        "14631-6",
        "Totaal bilirubine",
        "umol/L",
        _rule(
            "bilirubin",
            "14631-6",
            "Totaal bilirubine",
            "umol/L",
            "serum_or_plasma",
            "2",
            "21",
            _cmp,
        ),
    ),
    _entry(
        "1751-7",
        "Albumine",
        "g/L",
        _rule("albumin", "1751-7", "Albumine", "g/L", "serum", "34", "54", _cmp),
    ),
    _entry(
        "5902-2",
        "Protrombinetijd",
        "s",
        _rule(
            "pt",
            "5902-2",
            "Protrombinetijd",
            "s",
            "plasma",
            "11",
            "13.5",
            "ucsf-pt-2025",
            applicability=_app("any", None, "no_anticoagulant"),
            limitations=_anticoagulant,
        ),
    ),
    _entry(
        "3173-2",
        "aPTT stolling",
        "s",
        _rule(
            "aptt",
            "3173-2",
            "aPTT stolling",
            "s",
            "plasma",
            "25",
            "35",
            "ucsf-ptt-2025",
            applicability=_app("any", None, "no_anticoagulant"),
            limitations=_anticoagulant,
        ),
    ),
    _entry(
        "6301-6",
        "INR stolling",
        None,
        _rule(
            "inr",
            "6301-6",
            "INR stolling",
            None,
            "plasma",
            "0.8",
            "1.1",
            "ucsf-pt-2025",
            applicability=_app("any", None, "no_anticoagulant"),
            limitations=_anticoagulant,
        ),
    ),
    _entry(
        "14749-6",
        "Glucose",
        "mmol/L",
        _rule(
            "glucose-fasting",
            "14749-6",
            "Glucose",
            "mmol/L",
            "serum_or_plasma",
            "3.9",
            "5.6",
            _cmp,
            applicability=_app("any", None, "fasting_confirmed"),
            limitations=("Requires confirmed fasting for at least eight hours.",),
        ),
    ),
    _entry(
        "59261-8",
        "HbA1c IFCC",
        "mmol/mol",
        _rule(
            "hba1c-ifcc",
            "59261-8",
            "HbA1c IFCC",
            "mmol/mol",
            "whole_blood",
            "20",
            "41",
            "nwl-hba1c-2025",
            applicability=_app(
                "any",
                None,
                "no_renal_failure",
                "no_anemia",
                "no_hemoglobinopathy",
                "no_hiv",
                "stable_red_cell_turnover",
            ),
            limitations=(
                "Healthy reference interval, not a diabetes diagnostic cutoff or treatment target.",
            ),
            method="ion_exchange_chromatography_ifcc_traceable",
        ),
    ),
    _entry(
        "2000-8",
        "Calcium",
        "mmol/L",
        _rule(
            "calcium",
            "2000-8",
            "Calcium",
            "mmol/L",
            "serum_or_plasma",
            "2.13",
            "2.55",
            _cmp,
        ),
    ),
    _entry(
        "2601-3",
        "Magnesium",
        "mmol/L",
        _rule(
            "magnesium",
            "2601-3",
            "Magnesium",
            "mmol/L",
            "serum",
            "0.70",
            "0.91",
            "ucsf-magnesium-2025",
        ),
    ),
    _entry(
        "14879-1",
        "Fosfaat",
        "mmol/L",
        _rule(
            "phosphate",
            "14879-1",
            "Fosfaat",
            "mmol/L",
            "serum_or_plasma",
            "0.8",
            "1.5",
            "pathology-harmony-adult-2011",
        ),
        catalogue_version="general-academic-adult-v2",
    ),
    _entry(
        "2857-1",
        "PSA totaal",
        "ug/L",
        unavailable="ABIM publishes no established PSA reference range; Mayo age limits use method-specific LOINC 83112-3 and are not assigned to generic LOINC 2857-1.",
        provenance_sources=("abim-reference-ranges-2026", "mayo-psa-2026"),
    ),
)
