# Generated by Django 6.0 on 2026-07-20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emr", "0077_tagconfig_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicationrequest",
            name="client_request_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="medicationrequest",
            name="client_request_payload_hash",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddConstraint(
            model_name="medicationrequest",
            constraint=models.UniqueConstraint(
                fields=("client_request_id",),
                name="medreq_client_request_id_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="medicationrequest",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(
                        client_request_id__isnull=True,
                        client_request_payload_hash__isnull=True,
                    )
                    | models.Q(
                        client_request_id__isnull=False,
                        client_request_payload_hash__isnull=False,
                    )
                ),
                name="medreq_client_id_hash_pair_ck",
            ),
        ),
    ]
