# Generated by Django 6.0 on 2026-07-20 00:16

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emr", "0079_formsubmission_versioned_workflow"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FormSubmissionArtifactCommand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                (
                    "created_date",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "modified_date",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                ("deleted", models.BooleanField(db_index=True, default=False)),
                ("history", models.JSONField(default=dict)),
                ("meta", models.JSONField(default=dict)),
                ("client_request_id", models.UUIDField()),
                ("payload_hash", models.CharField(max_length=64)),
                ("source_version", models.PositiveIntegerField()),
                ("source_snapshot_hash", models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name="reportupload",
            name="artifact_sha256",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="reportupload",
            name="encounter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="form_submission_artifacts",
                to="emr.encounter",
            ),
        ),
        migrations.AddField(
            model_name="reportupload",
            name="form_submission",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="printable_artifacts",
                to="emr.formsubmission",
            ),
        ),
        migrations.AddField(
            model_name="reportupload",
            name="generated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reportupload",
            name="generated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="generated_form_submission_artifacts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="reportupload",
            name="patient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="form_submission_artifacts",
                to="emr.patient",
            ),
        ),
        migrations.AddField(
            model_name="reportupload",
            name="source_snapshot_hash",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="reportupload",
            name="source_version",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reportupload",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="emr.template",
            ),
        ),
        migrations.AddConstraint(
            model_name="reportupload",
            constraint=models.UniqueConstraint(
                fields=("form_submission", "source_version"),
                name="formartifact_source_version_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="reportupload",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("artifact_sha256", ""),
                        ("encounter__isnull", True),
                        ("form_submission__isnull", True),
                        ("generated_at__isnull", True),
                        ("generated_by__isnull", True),
                        ("patient__isnull", True),
                        ("source_snapshot_hash", ""),
                        ("source_version__isnull", True),
                        ("template__isnull", False),
                    ),
                    models.Q(
                        ("encounter__isnull", False),
                        ("form_submission__isnull", False),
                        ("generated_at__isnull", False),
                        ("generated_by__isnull", False),
                        ("patient__isnull", False),
                        ("report_type", "encounter_report"),
                        ("source_version__isnull", False),
                        ("template__isnull", True),
                        ("upload_completed", True),
                        models.Q(("source_snapshot_hash", ""), _negated=True),
                        models.Q(("artifact_sha256", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="formartifact_provenance_ck",
            ),
        ),
        migrations.AddField(
            model_name="formsubmissionartifactcommand",
            name="actor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="formsubmissionartifactcommand",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="formsubmissionartifactcommand",
            name="encounter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="emr.encounter"
            ),
        ),
        migrations.AddField(
            model_name="formsubmissionartifactcommand",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="emr.patient"
            ),
        ),
        migrations.AddField(
            model_name="formsubmissionartifactcommand",
            name="result_artifact",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="idempotency_commands",
                to="emr.reportupload",
            ),
        ),
        migrations.AddField(
            model_name="formsubmissionartifactcommand",
            name="source_submission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="artifact_commands",
                to="emr.formsubmission",
            ),
        ),
        migrations.AddField(
            model_name="formsubmissionartifactcommand",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_updated_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="formsubmissionartifactcommand",
            constraint=models.UniqueConstraint(
                fields=("client_request_id",), name="formartifact_cmd_request_id_uniq"
            ),
        ),
    ]
