# Generated by Django 6.0 on 2026-07-20 00:47

import hashlib
import json
import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_template_content_hashes(apps, schema_editor):
    Template = apps.get_model("emr", "Template")
    for template in Template.objects.all().iterator():
        canonical = {
            "context": template.context,
            "default_format": template.default_format,
            "name": template.name,
            "options": template.options,
            "slug": template.slug,
            "template_data": template.template_data,
            "template_type": template.template_type,
        }
        encoded = json.dumps(
            canonical,
            ensure_ascii=False,
            separators=(",", ":"),
            sort_keys=True,
        ).encode()
        template.content_hash = hashlib.sha256(encoded).hexdigest()
        template.save(update_fields=["content_hash"])


class Migration(migrations.Migration):
    dependencies = [
        ("emr", "0080_form_submission_artifact"),
        ("facility", "0484_remove_facility_discount_codes_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="template",
            name="content_hash",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="template",
            name="resource_version",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.RunPython(
            backfill_template_content_hashes,
            migrations.RunPython.noop,
        ),
        migrations.CreateModel(
            name="CorrespondenceCompilation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                (
                    "created_date",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "modified_date",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                ("deleted", models.BooleanField(db_index=True, default=False)),
                ("history", models.JSONField(default=dict)),
                ("meta", models.JSONField(default=dict)),
                ("source_fingerprint", models.CharField(max_length=64)),
                ("form_source_version", models.PositiveIntegerField()),
                ("form_source_hash", models.CharField(max_length=64)),
                ("form_artifact_hash", models.CharField(max_length=64)),
                ("template_version", models.PositiveIntegerField()),
                ("template_hash", models.CharField(max_length=64)),
                ("medication_sources", models.JSONField(default=list)),
                ("source_provenance", models.JSONField(default=dict)),
                ("compiled_text", models.TextField()),
                ("compiled_html", models.TextField()),
                ("compiled_hash", models.CharField(max_length=64)),
                ("compiled_at", models.DateTimeField()),
                ("status", models.CharField(default="compiled", max_length=32)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="authored_correspondence_compilations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="emr.facilityorganization",
                    ),
                ),
                (
                    "encounter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="emr.encounter"
                    ),
                ),
                (
                    "encounter_reason",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="emr.tagconfig"
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="facility.facility",
                    ),
                ),
                (
                    "form_artifact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="correspondence_compilations",
                        to="emr.reportupload",
                    ),
                ),
                (
                    "form_submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="correspondence_compilations",
                        to="emr.formsubmission",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="emr.patient"
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="correspondence_compilations",
                        to="emr.template",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CorrespondenceCompileCommand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                (
                    "created_date",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "modified_date",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                ("deleted", models.BooleanField(db_index=True, default=False)),
                ("history", models.JSONField(default=dict)),
                ("meta", models.JSONField(default=dict)),
                ("client_request_id", models.UUIDField()),
                ("payload_hash", models.CharField(max_length=64)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "encounter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="emr.encounter"
                    ),
                ),
                (
                    "form_submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="emr.formsubmission",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="emr.patient"
                    ),
                ),
                (
                    "result_compilation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="idempotency_commands",
                        to="emr.correspondencecompilation",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="correspondencecompilation",
            constraint=models.UniqueConstraint(
                fields=("source_fingerprint",),
                name="corrcompile_source_fingerprint_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="correspondencecompilation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status", "compiled"),
                    models.Q(("form_source_hash", ""), _negated=True),
                    models.Q(("form_artifact_hash", ""), _negated=True),
                    models.Q(("template_hash", ""), _negated=True),
                    models.Q(("compiled_hash", ""), _negated=True),
                    models.Q(("compiled_html", ""), _negated=True),
                    models.Q(("compiled_text", ""), _negated=True),
                ),
                name="corrcompile_complete_snapshot_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="correspondencecompilecommand",
            constraint=models.UniqueConstraint(
                fields=("client_request_id",), name="corrcompile_cmd_request_id_uniq"
            ),
        ),
    ]
