# Generated by Django 6.0 on 2026-07-20 03:32

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emr", "0081_correspondence_compilation"),
        ("facility", "0484_remove_facility_discount_codes_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CorrespondenceRecipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                (
                    "created_date",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "modified_date",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                ("deleted", models.BooleanField(db_index=True, default=False)),
                ("history", models.JSONField(default=dict)),
                ("meta", models.JSONField(default=dict)),
                (
                    "recipient_kind",
                    models.CharField(default="healthcare_professional", max_length=64),
                ),
                ("display_name", models.CharField(max_length=255)),
                ("professional_role", models.CharField(max_length=255)),
                (
                    "qualification",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "registration",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("organization_name", models.CharField(max_length=255)),
                ("postal_address", models.JSONField(default=dict)),
                ("channel_type", models.CharField(max_length=64)),
                ("channel_identifier", models.CharField(max_length=512)),
                ("source_type", models.CharField(max_length=64)),
                ("source_reference", models.CharField(max_length=255)),
                ("source_provenance", models.JSONField(default=dict)),
                ("active", models.BooleanField(default=True)),
                ("verified", models.BooleanField(default=False)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("resource_version", models.PositiveIntegerField(default=1)),
                (
                    "content_hash",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="correspondence_recipients",
                        to="facility.facility",
                    ),
                ),
                (
                    "healthcare_service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="emr.healthcareservice",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="emr.organization",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="correspondence_recipients",
                        to="emr.patient",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="verified_correspondence_recipients",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CorrespondenceReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                (
                    "created_date",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "modified_date",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                ("deleted", models.BooleanField(db_index=True, default=False)),
                ("history", models.JSONField(default=dict)),
                ("meta", models.JSONField(default=dict)),
                ("compilation_hash", models.CharField(max_length=64)),
                ("source_fingerprint", models.CharField(max_length=64)),
                ("recipient_version", models.PositiveIntegerField()),
                ("recipient_hash", models.CharField(max_length=64)),
                ("author_snapshot", models.JSONField(default=dict)),
                ("recipient_snapshot", models.JSONField(default=dict)),
                ("reviewed_at", models.DateTimeField()),
                ("review_hash", models.CharField(max_length=64)),
                ("status", models.CharField(default="reviewed", max_length=32)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="authored_correspondence_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "compilation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reviews",
                        to="emr.correspondencecompilation",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="emr.facilityorganization",
                    ),
                ),
                (
                    "encounter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="emr.encounter"
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="facility.facility",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="emr.patient"
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reviews",
                        to="emr.correspondencerecipient",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="performed_correspondence_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CorrespondenceReviewCommand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                (
                    "created_date",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "modified_date",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                ("deleted", models.BooleanField(db_index=True, default=False)),
                ("history", models.JSONField(default=dict)),
                ("meta", models.JSONField(default=dict)),
                ("client_request_id", models.UUIDField()),
                ("payload_hash", models.CharField(max_length=64)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "compilation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="emr.correspondencecompilation",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "encounter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="emr.encounter"
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="emr.patient"
                    ),
                ),
                (
                    "result_review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="idempotency_commands",
                        to="emr.correspondencereview",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="correspondencerecipient",
            constraint=models.UniqueConstraint(
                fields=("facility", "patient", "source_type", "source_reference"),
                name="corrrecipient_source_scope_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="correspondencerecipient",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("verified", False),
                    models.Q(
                        ("verified_at__isnull", False), ("verified_by__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="corrrecipient_verified_audit_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="correspondencereview",
            constraint=models.UniqueConstraint(
                fields=("compilation",), name="corrreview_compilation_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="correspondencereview",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status", "reviewed"),
                    models.Q(("compilation_hash", ""), _negated=True),
                    models.Q(("source_fingerprint", ""), _negated=True),
                    models.Q(("recipient_hash", ""), _negated=True),
                    models.Q(("review_hash", ""), _negated=True),
                    models.Q(("author_snapshot", {}), _negated=True),
                    models.Q(("recipient_snapshot", {}), _negated=True),
                ),
                name="corrreview_complete_snapshot_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="correspondencereviewcommand",
            constraint=models.UniqueConstraint(
                fields=("client_request_id",), name="corrreview_cmd_request_id_uniq"
            ),
        ),
    ]
