# Generated by Django 6.0 on 2026-07-20 07:07

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emr", "0084_correspondence_letter_workflow"),
        ("facility", "0484_remove_facility_discount_codes_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CorrespondenceDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                (
                    "created_date",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "modified_date",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                ("deleted", models.BooleanField(db_index=True, default=False)),
                ("history", models.JSONField(default=dict)),
                ("meta", models.JSONField(default=dict)),
                ("revision_version", models.PositiveIntegerField()),
                ("revision_hash", models.CharField(max_length=64)),
                ("artifact_sha256", models.CharField(max_length=64)),
                ("review_hash", models.CharField(max_length=64)),
                ("recipient_version", models.PositiveIntegerField()),
                ("recipient_hash", models.CharField(max_length=64)),
                ("channel_type", models.CharField(max_length=64)),
                ("adapter_name", models.CharField(max_length=64)),
                ("adapter_version", models.CharField(max_length=32)),
                ("provider_idempotency_key", models.CharField(max_length=64)),
                ("delivery_hash", models.CharField(max_length=64)),
                (
                    "correction_case_reference",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "artifact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="correspondence_deliveries",
                        to="emr.reportupload",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="emr.facilityorganization",
                    ),
                ),
                (
                    "encounter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="emr.encounter"
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="facility.facility",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="emr.patient"
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deliveries",
                        to="emr.correspondencerecipient",
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deliveries",
                        to="emr.correspondencereview",
                    ),
                ),
                (
                    "revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deliveries",
                        to="emr.correspondenceletterrevision",
                    ),
                ),
                (
                    "supersedes",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="superseded_by_deliveries",
                        to="emr.correspondencedelivery",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CorrespondenceDeliveryAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                (
                    "created_date",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "modified_date",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                ("deleted", models.BooleanField(db_index=True, default=False)),
                ("history", models.JSONField(default=dict)),
                ("meta", models.JSONField(default=dict)),
                ("attempt_number", models.PositiveIntegerField()),
                ("client_request_id", models.UUIDField()),
                ("payload_hash", models.CharField(max_length=64)),
                ("command_type", models.CharField(max_length=16)),
                ("requested_at", models.DateTimeField()),
                ("adapter_name", models.CharField(max_length=64)),
                ("adapter_version", models.CharField(max_length=32)),
                ("provider_idempotency_key", models.CharField(max_length=64)),
                ("attempt_hash", models.CharField(max_length=64)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "delivery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attempts",
                        to="emr.correspondencedelivery",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CorrespondenceDeliveryEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                (
                    "created_date",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "modified_date",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                ("deleted", models.BooleanField(db_index=True, default=False)),
                ("history", models.JSONField(default=dict)),
                ("meta", models.JSONField(default=dict)),
                ("sequence", models.PositiveIntegerField()),
                ("event_type", models.CharField(max_length=32)),
                ("certainty", models.CharField(max_length=32)),
                ("occurred_at", models.DateTimeField()),
                ("actor_type", models.CharField(max_length=16)),
                ("safe_code", models.CharField(blank=True, default="", max_length=64)),
                (
                    "provider_ack_reference",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "provider_ack_hash",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("provider_ack_at", models.DateTimeField(blank=True, null=True)),
                (
                    "previous_event_hash",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("event_hash", models.CharField(max_length=64)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="correspondence_delivery_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="emr.correspondencedeliveryattempt",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "delivery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="emr.correspondencedelivery",
                    ),
                ),
                (
                    "previous_event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="next_events",
                        to="emr.correspondencedeliveryevent",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="correspondencedeliveryattempt",
            name="previous_terminal_event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="retry_attempts",
                to="emr.correspondencedeliveryevent",
            ),
        ),
        migrations.CreateModel(
            name="CorrespondenceSyntheticProviderInvocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                (
                    "created_date",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "modified_date",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                ("deleted", models.BooleanField(db_index=True, default=False)),
                ("history", models.JSONField(default=dict)),
                ("meta", models.JSONField(default=dict)),
                ("provider_idempotency_key", models.CharField(max_length=64)),
                ("attempt_number", models.PositiveIntegerField()),
                ("request_hash", models.CharField(max_length=64)),
                ("started_at", models.DateTimeField()),
                ("marker_hash", models.CharField(max_length=64)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CorrespondenceSyntheticProviderReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                (
                    "created_date",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "modified_date",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                ("deleted", models.BooleanField(db_index=True, default=False)),
                ("history", models.JSONField(default=dict)),
                ("meta", models.JSONField(default=dict)),
                ("provider_idempotency_key", models.CharField(max_length=64)),
                ("attempt_number", models.PositiveIntegerField()),
                ("request_hash", models.CharField(max_length=64)),
                ("outcome_state", models.CharField(max_length=32)),
                ("safe_code", models.CharField(max_length=64)),
                (
                    "provider_ack_reference",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "provider_ack_hash",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("recorded_at", models.DateTimeField()),
                ("receipt_hash", models.CharField(max_length=64)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="correspondencedelivery",
            constraint=models.UniqueConstraint(
                fields=("revision",), name="corrdelivery_revision_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="correspondencedelivery",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("revision_hash", ""), _negated=True),
                    models.Q(("artifact_sha256", ""), _negated=True),
                    models.Q(("review_hash", ""), _negated=True),
                    models.Q(("recipient_hash", ""), _negated=True),
                    models.Q(("provider_idempotency_key", ""), _negated=True),
                    models.Q(("delivery_hash", ""), _negated=True),
                ),
                name="corrdelivery_hashes_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="correspondencedelivery",
            constraint=models.CheckConstraint(
                condition=models.Q(("pk", models.F("supersedes")), _negated=True),
                name="corrdelivery_not_self_supersede_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="correspondencedeliveryevent",
            constraint=models.UniqueConstraint(
                fields=("delivery", "sequence"), name="corrdelivery_event_sequence_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="correspondencedeliveryevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "event_type__in",
                        [
                            "dispatch_pending",
                            "dispatching",
                            "acknowledged",
                            "failed_retryable",
                            "failed_terminal",
                            "outcome_unknown",
                        ],
                    )
                ),
                name="corrdelivery_event_type_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="correspondencedeliveryevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "certainty__in",
                        [
                            "not_attempted",
                            "attempting",
                            "acknowledged",
                            "not_delivered",
                            "unknown",
                        ],
                    )
                ),
                name="corrdelivery_event_certainty_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="correspondencedeliveryevent",
            constraint=models.CheckConstraint(
                condition=models.Q(("actor_type__in", ["user", "system"])),
                name="corrdelivery_event_actor_type_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="correspondencedeliveryevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("actor__isnull", False), ("actor_type", "user")),
                    models.Q(("actor__isnull", True), ("actor_type", "system")),
                    _connector="OR",
                ),
                name="corrdelivery_event_actor_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="correspondencedeliveryevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("certainty", "not_attempted"),
                        ("event_type", "dispatch_pending"),
                        ("provider_ack_at__isnull", True),
                        ("provider_ack_hash", ""),
                        ("provider_ack_reference", ""),
                    ),
                    models.Q(
                        ("certainty", "attempting"),
                        ("event_type", "dispatching"),
                        ("provider_ack_at__isnull", True),
                        ("provider_ack_hash", ""),
                        ("provider_ack_reference", ""),
                    ),
                    models.Q(
                        ("certainty", "acknowledged"),
                        ("event_type", "acknowledged"),
                        ("provider_ack_at__isnull", False),
                        ("provider_ack_hash__gt", ""),
                        ("provider_ack_reference__gt", ""),
                    ),
                    models.Q(
                        ("certainty", "not_delivered"),
                        ("event_type__in", ["failed_retryable", "failed_terminal"]),
                        ("provider_ack_at__isnull", True),
                        ("provider_ack_hash", ""),
                        ("provider_ack_reference", ""),
                    ),
                    models.Q(
                        ("certainty", "unknown"),
                        ("event_type", "outcome_unknown"),
                        ("provider_ack_at__isnull", True),
                        ("provider_ack_hash", ""),
                        ("provider_ack_reference", ""),
                    ),
                    _connector="OR",
                ),
                name="corrdelivery_event_outcome_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="correspondencedeliveryevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("previous_event__isnull", True),
                        ("previous_event_hash", ""),
                        ("sequence", 1),
                    ),
                    models.Q(
                        ("previous_event__isnull", False),
                        ("previous_event_hash__gt", ""),
                        ("sequence__gt", 1),
                    ),
                    _connector="OR",
                ),
                name="corrdelivery_event_chain_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="correspondencedeliveryattempt",
            constraint=models.UniqueConstraint(
                fields=("client_request_id",), name="corrdelivery_attempt_cmd_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="correspondencedeliveryattempt",
            constraint=models.UniqueConstraint(
                fields=("delivery", "attempt_number"),
                name="corrdelivery_attempt_number_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="correspondencedeliveryattempt",
            constraint=models.UniqueConstraint(
                condition=models.Q(("previous_terminal_event__isnull", False)),
                fields=("delivery", "previous_terminal_event"),
                name="corrdelivery_retry_trigger_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="correspondencedeliveryattempt",
            constraint=models.CheckConstraint(
                condition=models.Q(("command_type__in", ["send", "retry"])),
                name="corrdelivery_attempt_cmd_type_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="correspondencedeliveryattempt",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("payload_hash", ""), _negated=True),
                    models.Q(("provider_idempotency_key", ""), _negated=True),
                    models.Q(("attempt_hash", ""), _negated=True),
                ),
                name="corrdelivery_attempt_hashes_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="correspondencedeliveryattempt",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("created_by", models.F("requested_by")),
                    ("updated_by", models.F("requested_by")),
                ),
                name="corrdelivery_attempt_actor_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="correspondencedeliveryattempt",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("attempt_number", 1),
                        ("command_type", "send"),
                        ("previous_terminal_event__isnull", True),
                    ),
                    models.Q(
                        ("attempt_number__gt", 1),
                        ("command_type", "retry"),
                        ("previous_terminal_event__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="corrdelivery_attempt_lineage_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="correspondencesyntheticproviderinvocation",
            constraint=models.UniqueConstraint(
                fields=("provider_idempotency_key", "attempt_number"),
                name="corrsynthetic_invocation_key_attempt_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="correspondencesyntheticproviderinvocation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("provider_idempotency_key", ""), _negated=True),
                    models.Q(("request_hash", ""), _negated=True),
                    models.Q(("marker_hash", ""), _negated=True),
                ),
                name="corrsynthetic_invocation_hashes_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="correspondencesyntheticproviderreceipt",
            constraint=models.UniqueConstraint(
                fields=("provider_idempotency_key",),
                name="corrsynthetic_receipt_key_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="correspondencesyntheticproviderreceipt",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "outcome_state__in",
                        [
                            "acknowledged",
                            "failed_retryable",
                            "failed_terminal",
                            "outcome_unknown",
                        ],
                    )
                ),
                name="corrsynthetic_receipt_outcome_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="correspondencesyntheticproviderreceipt",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("provider_idempotency_key", ""), _negated=True),
                    models.Q(("request_hash", ""), _negated=True),
                    models.Q(("safe_code", ""), _negated=True),
                    models.Q(("receipt_hash", ""), _negated=True),
                ),
                name="corrsynthetic_receipt_hashes_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="correspondencesyntheticproviderreceipt",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("outcome_state", "acknowledged"),
                        ("provider_ack_hash__gt", ""),
                        ("provider_ack_reference__gt", ""),
                    ),
                    models.Q(
                        (
                            "outcome_state__in",
                            ["failed_retryable", "failed_terminal", "outcome_unknown"],
                        ),
                        ("provider_ack_hash", ""),
                        ("provider_ack_reference", ""),
                    ),
                    _connector="OR",
                ),
                name="corrsynthetic_receipt_ack_ck",
            ),
        ),
    ]
