# Generated by Django 6.0 on 2026-07-20 11:04

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def validate_pre_replacement_state(apps, schema_editor):
    correction_case_model = apps.get_model("emr", "CorrespondenceCorrectionCase")
    alias = schema_editor.connection.alias
    invalid_cases = correction_case_model._base_manager.using(alias).exclude(  # noqa: SLF001
        status="open",
        resolved_at__isnull=True,
        resolved_by__isnull=True,
        replacement_status="not_started",
        replacement_compilation__isnull=True,
        replacement_review__isnull=True,
        replacement_revision__isnull=True,
        replacement_artifact__isnull=True,
        replacement_delivery__isnull=True,
    )
    invalid_count = invalid_cases.count()
    if invalid_count:
        message = (
            "legacy correspondence correction cases contain pre-11-C state; "
            f"count={invalid_count}"
        )
        raise RuntimeError(message)


class Migration(migrations.Migration):
    dependencies = [
        ("emr", "0087_correspondence_continuity"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(
            validate_pre_replacement_state,
            migrations.RunPython.noop,
        ),
        migrations.CreateModel(
            name="CorrespondenceCorrectionCommand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                (
                    "created_date",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "modified_date",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                ("deleted", models.BooleanField(db_index=True, default=False)),
                ("history", models.JSONField(default=dict)),
                ("meta", models.JSONField(default=dict)),
                ("client_request_id", models.UUIDField()),
                ("payload_hash", models.CharField(max_length=64)),
                ("command_hash", models.CharField(max_length=64)),
                ("command_type", models.CharField(max_length=32)),
                ("expected_case_version", models.PositiveIntegerField()),
                ("expected_case_hash", models.CharField(max_length=64)),
                ("resulting_case_version", models.PositiveIntegerField()),
                ("resulting_case_hash", models.CharField(max_length=64)),
                ("result_snapshot", models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="CorrespondencePaperReconciliationAttestation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                (
                    "created_date",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "modified_date",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                ("deleted", models.BooleanField(db_index=True, default=False)),
                ("history", models.JSONField(default=dict)),
                ("meta", models.JSONField(default=dict)),
                ("artifact_hash", models.CharField(max_length=64)),
                ("attestation_type", models.CharField(max_length=64)),
                ("attested_at", models.DateTimeField()),
                ("attestation_hash", models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name="CorrespondenceReplacementAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                (
                    "created_date",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "modified_date",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                ("deleted", models.BooleanField(db_index=True, default=False)),
                ("history", models.JSONField(default=dict)),
                ("meta", models.JSONField(default=dict)),
                ("attempt_number", models.PositiveIntegerField()),
                ("source_head_hash", models.CharField(max_length=64)),
                ("source_correction_hash", models.CharField(max_length=64)),
                ("source_version", models.PositiveIntegerField()),
                ("source_snapshot_hash", models.CharField(max_length=64)),
                ("form_artifact_hash", models.CharField(max_length=64)),
                ("started_at", models.DateTimeField()),
                ("attempt_hash", models.CharField(max_length=64)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="correspondencecorrectioncase",
            name="corrcase_resolution_ck",
        ),
        migrations.RemoveConstraint(
            model_name="correspondencecorrectioncase",
            name="corrcase_replacement_ck",
        ),
        migrations.RemoveConstraint(
            model_name="correspondencecorrectioncase",
            name="corrcase_replace_prefix_ck",
        ),
        migrations.RemoveConstraint(
            model_name="correspondencecorrectionevent",
            name="correvent_state_ck",
        ),
        migrations.RemoveConstraint(
            model_name="correspondencecorrectionevent",
            name="correvent_source_ck",
        ),
        migrations.AddField(
            model_name="correspondencecorrectioncase",
            name="replacement_delivery_certainty",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="correspondencecorrectioncase",
            name="replacement_delivery_state",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="correspondencecorrectioncase",
            name="resolution_mode",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="correspondencecorrectioncommand",
            name="actor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="correspondence_correction_commands",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="correspondencecorrectioncommand",
            name="case",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="commands",
                to="emr.correspondencecorrectioncase",
            ),
        ),
        migrations.AddField(
            model_name="correspondencecorrectioncommand",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="correspondencecorrectioncommand",
            name="result_artifact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="correction_commands",
                to="emr.reportupload",
            ),
        ),
        migrations.AddField(
            model_name="correspondencecorrectioncommand",
            name="result_delivery",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="correction_commands",
                to="emr.correspondencedelivery",
            ),
        ),
        migrations.AddField(
            model_name="correspondencecorrectioncommand",
            name="result_revision",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="correction_commands",
                to="emr.correspondenceletterrevision",
            ),
        ),
        migrations.AddField(
            model_name="correspondencecorrectioncommand",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_updated_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="correspondencecorrectionevent",
            name="command",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="case_event",
                to="emr.correspondencecorrectioncommand",
            ),
        ),
        migrations.AddField(
            model_name="correspondencepaperreconciliationattestation",
            name="attested_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="correspondence_paper_attestations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="correspondencepaperreconciliationattestation",
            name="case",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="paper_attestations",
                to="emr.correspondencecorrectioncase",
            ),
        ),
        migrations.AddField(
            model_name="correspondencepaperreconciliationattestation",
            name="controlled_copy_artifact",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="paper_reconciliation_attestations",
                to="emr.reportupload",
            ),
        ),
        migrations.AddField(
            model_name="correspondencepaperreconciliationattestation",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="correspondencepaperreconciliationattestation",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_updated_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="correspondencecorrectioncommand",
            name="result_attestation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="correction_commands",
                to="emr.correspondencepaperreconciliationattestation",
            ),
        ),
        migrations.AddField(
            model_name="correspondencereplacementattempt",
            name="case",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="replacement_attempts",
                to="emr.correspondencecorrectioncase",
            ),
        ),
        migrations.AddField(
            model_name="correspondencereplacementattempt",
            name="compilation",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="replacement_attempt",
                to="emr.correspondencecompilation",
            ),
        ),
        migrations.AddField(
            model_name="correspondencereplacementattempt",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="correspondencereplacementattempt",
            name="form_artifact",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="correspondence_replacement_attempts",
                to="emr.reportupload",
            ),
        ),
        migrations.AddField(
            model_name="correspondencereplacementattempt",
            name="initial_revision",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="replacement_attempt_started",
                to="emr.correspondenceletterrevision",
            ),
        ),
        migrations.AddField(
            model_name="correspondencereplacementattempt",
            name="review",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="replacement_attempt",
                to="emr.correspondencereview",
            ),
        ),
        migrations.AddField(
            model_name="correspondencereplacementattempt",
            name="source_correction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="replacement_attempts",
                to="emr.correspondencesourcecorrection",
            ),
        ),
        migrations.AddField(
            model_name="correspondencereplacementattempt",
            name="source_head",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="replacement_attempts",
                to="emr.formsubmissionserieshead",
            ),
        ),
        migrations.AddField(
            model_name="correspondencereplacementattempt",
            name="source_submission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="correspondence_replacement_attempts",
                to="emr.formsubmission",
            ),
        ),
        migrations.AddField(
            model_name="correspondencereplacementattempt",
            name="started_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="started_correspondence_replacements",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="correspondencereplacementattempt",
            name="supersedes_attempt",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="superseded_by_attempts",
                to="emr.correspondencereplacementattempt",
            ),
        ),
        migrations.AddField(
            model_name="correspondencereplacementattempt",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_updated_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="correspondencepaperreconciliationattestation",
            name="replacement_attempt",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="paper_attestations",
                to="emr.correspondencereplacementattempt",
            ),
        ),
        migrations.AddField(
            model_name="correspondencecorrectioncommand",
            name="result_attempt",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="result_commands",
                to="emr.correspondencereplacementattempt",
            ),
        ),
        migrations.AddField(
            model_name="correspondencecorrectioncommand",
            name="target_attempt",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="targeted_commands",
                to="emr.correspondencereplacementattempt",
            ),
        ),
        migrations.AddField(
            model_name="correspondencecorrectioncase",
            name="replacement_attempt",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="current_for_cases",
                to="emr.correspondencereplacementattempt",
            ),
        ),
        migrations.AddField(
            model_name="correspondencecorrectionevent",
            name="replacement_attempt",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="case_events",
                to="emr.correspondencereplacementattempt",
            ),
        ),
        migrations.AddConstraint(
            model_name="correspondencecorrectioncase",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("replacement_delivery__isnull", True),
                        ("replacement_delivery_certainty__isnull", True),
                        ("replacement_delivery_state__isnull", True),
                    ),
                    models.Q(
                        ("replacement_delivery__isnull", False),
                        (
                            "replacement_delivery_certainty__in",
                            [
                                "not_attempted",
                                "attempting",
                                "acknowledged",
                                "not_delivered",
                                "unknown",
                            ],
                        ),
                        (
                            "replacement_delivery_state__in",
                            [
                                "dispatch_pending",
                                "dispatching",
                                "acknowledged",
                                "failed_retryable",
                                "failed_terminal",
                                "outcome_unknown",
                            ],
                        ),
                    ),
                    _connector="OR",
                ),
                name="corrcase_replace_delivery_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="correspondencecorrectioncase",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("resolution_mode__isnull", True),
                        ("resolved_at__isnull", True),
                        ("resolved_by__isnull", True),
                        ("status", "open"),
                    ),
                    models.Q(
                        ("notification_status", "acknowledged"),
                        ("replacement_status", "acknowledged"),
                        ("resolution_mode", "replacement_acknowledged"),
                        ("resolved_at__isnull", False),
                        ("resolved_by__isnull", False),
                        ("status", "resolved"),
                        models.Q(
                            ("paper_reconciliation_status", "required"), _negated=True
                        ),
                    ),
                    models.Q(
                        ("delivery_certainty", "not_delivered"),
                        ("notification_status", "not_required"),
                        ("paper_reconciliation_status", "not_required"),
                        ("resolution_mode", "original_not_delivered"),
                        ("resolved_at__isnull", False),
                        ("resolved_by__isnull", False),
                        ("status", "resolved"),
                    ),
                    _connector="OR",
                ),
                name="corrcase_resolution_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="correspondencecorrectioncase",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("replacement_artifact__isnull", True),
                        ("replacement_attempt__isnull", True),
                        ("replacement_compilation__isnull", True),
                        ("replacement_delivery__isnull", True),
                        ("replacement_delivery_certainty__isnull", True),
                        ("replacement_delivery_state__isnull", True),
                        ("replacement_review__isnull", True),
                        ("replacement_revision__isnull", True),
                        ("replacement_status", "not_started"),
                    ),
                    models.Q(("replacement_status", "not_started"), _negated=True),
                    _connector="OR",
                ),
                name="corrcase_replacement_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="correspondencecorrectioncase",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("replacement_review__isnull", True),
                        models.Q(
                            ("replacement_attempt__isnull", False),
                            ("replacement_compilation__isnull", False),
                        ),
                        _connector="OR",
                    ),
                    models.Q(
                        ("replacement_revision__isnull", True),
                        ("replacement_review__isnull", False),
                        _connector="OR",
                    ),
                    models.Q(
                        ("replacement_artifact__isnull", True),
                        ("replacement_revision__isnull", False),
                        _connector="OR",
                    ),
                    models.Q(
                        ("replacement_delivery__isnull", True),
                        ("replacement_artifact__isnull", False),
                        _connector="OR",
                    ),
                    models.Q(
                        models.Q(("replacement_status", "acknowledged"), _negated=True),
                        ("replacement_delivery__isnull", False),
                        _connector="OR",
                    ),
                ),
                name="corrcase_replace_prefix_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="correspondencecorrectionevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("sequence__gt", 0),
                    (
                        "event_type__in",
                        [
                            "opened",
                            "source_advanced",
                            "delivery_classified",
                            "replacement_started",
                            "replacement_revised",
                            "replacement_finalized",
                            "replacement_delivery_linked",
                            "replacement_delivery_classified",
                            "paper_reconciled",
                            "resolved",
                        ],
                    ),
                    ("actor_type__in", ["user", "system"]),
                    models.Q(("safe_code", ""), _negated=True),
                    ("resulting_case_hash__regex", "^[0-9a-f]{64}$"),
                    ("event_hash__regex", "^[0-9a-f]{64}$"),
                ),
                name="correvent_state_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="correspondencecorrectionevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("command__isnull", True),
                        ("delivery_event__isnull", True),
                        ("event_type__in", ["opened", "source_advanced"]),
                        ("replacement_attempt__isnull", True),
                        ("source_correction__isnull", False),
                    ),
                    models.Q(
                        ("command__isnull", True),
                        ("delivery_event__isnull", False),
                        ("event_type", "delivery_classified"),
                        ("replacement_attempt__isnull", True),
                        ("source_correction__isnull", True),
                    ),
                    models.Q(
                        ("command__isnull", True),
                        ("delivery_event__isnull", False),
                        ("event_type", "replacement_delivery_classified"),
                        ("replacement_attempt__isnull", False),
                        ("source_correction__isnull", True),
                    ),
                    models.Q(
                        ("command__isnull", False),
                        ("delivery_event__isnull", True),
                        (
                            "event_type__in",
                            [
                                "replacement_started",
                                "replacement_revised",
                                "replacement_finalized",
                                "replacement_delivery_linked",
                                "paper_reconciled",
                                "resolved",
                            ],
                        ),
                        ("source_correction__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="correvent_source_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="correspondencereplacementattempt",
            constraint=models.UniqueConstraint(
                fields=("case", "attempt_number"), name="corrreplace_case_attempt_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="correspondencereplacementattempt",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("attempt_number__gt", 0),
                    ("source_version__gt", 0),
                    ("source_head_hash__regex", "^[0-9a-f]{64}$"),
                    ("source_correction_hash__regex", "^[0-9a-f]{64}$"),
                    ("source_snapshot_hash__regex", "^[0-9a-f]{64}$"),
                    ("form_artifact_hash__regex", "^[0-9a-f]{64}$"),
                    ("attempt_hash__regex", "^[0-9a-f]{64}$"),
                    ("created_by", models.F("started_by")),
                    ("updated_by", models.F("started_by")),
                ),
                name="corrreplace_snapshot_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="correspondencereplacementattempt",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("attempt_number", 1), ("supersedes_attempt__isnull", True)
                    ),
                    models.Q(
                        ("attempt_number__gt", 1), ("supersedes_attempt__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="corrreplace_lineage_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="correspondencepaperreconciliationattestation",
            constraint=models.UniqueConstraint(
                fields=("case", "replacement_attempt"),
                name="corrpaper_case_attempt_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="correspondencepaperreconciliationattestation",
            constraint=models.UniqueConstraint(
                fields=("case", "controlled_copy_artifact"),
                name="corrpaper_case_artifact_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="correspondencepaperreconciliationattestation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "attestation_type",
                        "corrected_copy_filed_prior_copy_reconciled",
                    ),
                    ("artifact_hash__regex", "^[0-9a-f]{64}$"),
                    ("attestation_hash__regex", "^[0-9a-f]{64}$"),
                    ("created_by", models.F("attested_by")),
                    ("updated_by", models.F("attested_by")),
                ),
                name="corrpaper_attestation_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="correspondencecorrectioncommand",
            constraint=models.UniqueConstraint(
                fields=("client_request_id",), name="corrcase_cmd_request_id_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="correspondencecorrectioncommand",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "command_type__in",
                        [
                            "start_replacement",
                            "revise_replacement",
                            "finalize_replacement",
                            "send_replacement",
                            "retry_replacement",
                            "attest_paper",
                            "resolve",
                        ],
                    ),
                    ("expected_case_version__gt", 0),
                    ("resulting_case_version__gt", 0),
                    ("payload_hash__regex", "^[0-9a-f]{64}$"),
                    ("command_hash__regex", "^[0-9a-f]{64}$"),
                    ("expected_case_hash__regex", "^[0-9a-f]{64}$"),
                    ("resulting_case_hash__regex", "^[0-9a-f]{64}$"),
                    models.Q(("result_snapshot", {}), _negated=True),
                    ("created_by", models.F("actor")),
                    ("updated_by", models.F("actor")),
                ),
                name="corrcase_cmd_snapshot_ck",
            ),
        ),
    ]
