# Generated by Django 6.0 on 2026-07-20 13:10

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emr", "0088_correspondence_replacement_workflow"),
        ("facility", "0484_remove_facility_discount_codes_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsultClosure",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("external_id", models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ("created_date", models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ("modified_date", models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ("deleted", models.BooleanField(db_index=True, default=False)),
                ("history", models.JSONField(default=dict)),
                ("meta", models.JSONField(default=dict)),
                ("closure_number", models.PositiveIntegerField()),
                ("policy_id", models.CharField(max_length=64)),
                ("policy_version", models.PositiveIntegerField()),
                ("policy_hash", models.CharField(max_length=64)),
                ("preflight_version", models.PositiveIntegerField()),
                ("preflight_hash", models.CharField(max_length=64)),
                ("form_source_version", models.PositiveIntegerField()),
                ("form_source_hash", models.CharField(max_length=64)),
                ("form_artifact_hash", models.CharField(max_length=64)),
                ("medication_outcome", models.CharField(max_length=32)),
                ("medication_actions", models.JSONField(default=list)),
                ("correspondence_outcome", models.CharField(max_length=32)),
                ("correspondence_delivery_event_sequence", models.PositiveIntegerField(blank=True, null=True)),
                ("correspondence_delivery_event_hash", models.CharField(blank=True, max_length=64, null=True)),
                ("correspondence_case_version", models.PositiveIntegerField(blank=True, null=True)),
                ("correspondence_case_hash", models.CharField(blank=True, max_length=64, null=True)),
                ("encounter_status", models.CharField(max_length=32)),
                ("token_status", models.CharField(max_length=32)),
                ("booking_status", models.CharField(max_length=32)),
                ("closed_at", models.DateTimeField()),
                ("closure_hash", models.CharField(max_length=64)),
                ("appointment", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="emr.tokenbooking")),
                ("closed_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="closed_consults", to=settings.AUTH_USER_MODEL)),
                ("correspondence_case", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="emr.correspondencecorrectioncase")),
                ("correspondence_compilation", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="emr.correspondencecompilation")),
                ("correspondence_delivery", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="emr.correspondencedelivery")),
                ("created_by", models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(app_label)s_%(class)s_created_by", to=settings.AUTH_USER_MODEL)),
                ("department", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="emr.facilityorganization")),
                ("encounter", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="consult_closures", to="emr.encounter")),
                ("facility", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="facility.facility")),
                ("form_artifact", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="emr.reportupload")),
                ("form_submission", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="emr.formsubmission")),
                ("patient", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="emr.patient")),
                ("previous_closure", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="superseded_by_closures", to="emr.consultclosure")),
                ("token", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="emr.token")),
                ("updated_by", models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(app_label)s_%(class)s_updated_by", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="ConsultClosureCommand",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("external_id", models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ("created_date", models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ("modified_date", models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ("deleted", models.BooleanField(db_index=True, default=False)),
                ("history", models.JSONField(default=dict)),
                ("meta", models.JSONField(default=dict)),
                ("client_request_id", models.UUIDField()),
                ("payload_hash", models.CharField(max_length=64)),
                ("command_hash", models.CharField(max_length=64)),
                ("result_snapshot", models.JSONField(default=dict)),
                ("actor", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="consult_closure_commands", to=settings.AUTH_USER_MODEL)),
                ("created_by", models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(app_label)s_%(class)s_created_by", to=settings.AUTH_USER_MODEL)),
                ("encounter", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="emr.encounter")),
                ("result_closure", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="commands", to="emr.consultclosure")),
                ("updated_by", models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(app_label)s_%(class)s_updated_by", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="ConsultClosureRecoveryTask",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("external_id", models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ("created_date", models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ("modified_date", models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ("deleted", models.BooleanField(db_index=True, default=False)),
                ("history", models.JSONField(default=dict)),
                ("meta", models.JSONField(default=dict)),
                ("status", models.CharField(max_length=16)),
                ("safe_code", models.CharField(max_length=64)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("recovery_hash", models.CharField(max_length=64)),
                ("closure", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="recovery_tasks", to="emr.consultclosure")),
                ("created_by", models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(app_label)s_%(class)s_created_by", to=settings.AUTH_USER_MODEL)),
                ("encounter", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="consult_closure_recovery_tasks", to="emr.encounter")),
                ("updated_by", models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(app_label)s_%(class)s_updated_by", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name="consultclosure",
            constraint=models.UniqueConstraint(fields=("encounter", "closure_number"), name="consultclosure_encounter_number_uniq"),
        ),
        migrations.AddConstraint(
            model_name="consultclosure",
            constraint=models.UniqueConstraint(fields=("preflight_hash",), name="consultclosure_preflight_hash_uniq"),
        ),
        migrations.AddConstraint(
            model_name="consultclosure",
            constraint=models.CheckConstraint(condition=models.Q(("closure_number__gt", 0), ("policy_version__gt", 0), ("preflight_version__gt", 0), ("form_source_version__gt", 0), ("policy_hash__regex", "^[0-9a-f]{64}$"), ("preflight_hash__regex", "^[0-9a-f]{64}$"), ("form_source_hash__regex", "^[0-9a-f]{64}$"), ("form_artifact_hash__regex", "^[0-9a-f]{64}$"), ("closure_hash__regex", "^[0-9a-f]{64}$"), ("encounter_status", "completed"), ("token_status", "FULFILLED"), ("booking_status", "fulfilled"), ("created_by", models.F("closed_by")), ("updated_by", models.F("closed_by"))), name="consultclosure_snapshot_ck"),
        ),
        migrations.AddConstraint(
            model_name="consultclosure",
            constraint=models.CheckConstraint(condition=models.Q(models.Q(("closure_number", 1), ("previous_closure__isnull", True)), models.Q(("closure_number__gt", 1), ("previous_closure__isnull", False)), _connector="OR"), name="consultclosure_lineage_ck"),
        ),
        migrations.AddConstraint(
            model_name="consultclosurecommand",
            constraint=models.UniqueConstraint(fields=("client_request_id",), name="consultclosure_cmd_request_uniq"),
        ),
        migrations.AddConstraint(
            model_name="consultclosurecommand",
            constraint=models.CheckConstraint(condition=models.Q(("payload_hash__regex", "^[0-9a-f]{64}$"), ("command_hash__regex", "^[0-9a-f]{64}$"), models.Q(("result_snapshot", {}), _negated=True), ("created_by", models.F("actor")), ("updated_by", models.F("actor"))), name="consultclosure_cmd_snapshot_ck"),
        ),
        migrations.AddConstraint(
            model_name="consultclosurerecoverytask",
            constraint=models.UniqueConstraint(condition=models.Q(("deleted", False), ("status", "pending")), fields=("encounter",), name="consultclosure_recovery_pending_uniq"),
        ),
        migrations.AddConstraint(
            model_name="consultclosurerecoverytask",
            constraint=models.CheckConstraint(condition=models.Q(models.Q(("resolved_at__isnull", True), ("status", "pending")), models.Q(("resolved_at__isnull", False), ("status", "resolved")), _connector="OR"), name="consultclosure_recovery_state_ck"),
        ),
        migrations.AddConstraint(
            model_name="consultclosurerecoverytask",
            constraint=models.CheckConstraint(condition=models.Q(("safe_code__regex", "^[a-z0-9_:-]{1,64}$"), ("recovery_hash__regex", "^[0-9a-f]{64}$")), name="consultclosure_recovery_hash_ck"),
        ),
    ]
