# Generated by Django 6.0 on 2026-07-20 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emr", "0089_consult_closure_workflow"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="consultclosurerecoverytask",
            name="consultclosure_recovery_state_ck",
        ),
        migrations.AddField(
            model_name="consultclosurerecoverytask",
            name="resolution_hash",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="consultclosurerecoverytask",
            name="resolution_payload_hash",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="consultclosurerecoverytask",
            name="resolution_request_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="consultclosurerecoverytask",
            name="resolved_by",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="resolved_consult_closure_recovery_tasks", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name="consultclosurerecoverytask",
            constraint=models.CheckConstraint(condition=models.Q(models.Q(("resolution_hash__isnull", True), ("resolution_payload_hash__isnull", True), ("resolution_request_id__isnull", True), ("resolved_at__isnull", True), ("resolved_by__isnull", True), ("status", "pending")), models.Q(("resolution_hash__regex", "^[0-9a-f]{64}$"), ("resolution_payload_hash__regex", "^[0-9a-f]{64}$"), ("resolution_request_id__isnull", False), ("resolved_at__isnull", False), ("resolved_by__isnull", False), ("status", "resolved")), _connector="OR"), name="consultclosure_recovery_state_ck"),
        ),
        migrations.AddConstraint(
            model_name="consultclosurerecoverytask",
            constraint=models.UniqueConstraint(condition=models.Q(("resolution_request_id__isnull", False)), fields=("resolution_request_id",), name="consultclosure_recovery_resolve_req_uniq"),
        ),
    ]
