# Generated by Django 6.0 on 2026-07-20 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emr", "0090_consult_closure_recovery_resolution"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="formsubmission",
            name="formsub_finalized_snapshot_ck",
        ),
        migrations.RemoveConstraint(
            model_name="formsubmissioncommand",
            name="formsub_cmd_type_ck",
        ),
        migrations.AddField(
            model_name="formsubmission",
            name="entered_in_error_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="formsubmission",
            name="entered_in_error_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="entered_in_error_form_submissions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="formsubmission",
            name="entered_in_error_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddConstraint(
            model_name="formsubmission",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("status", "submitted"),
                        ("workflow_finalized_at__isnull", False),
                        ("workflow_finalized_by__isnull", False),
                        ("finalized_snapshot_hash__regex", "^[0-9a-f]{64}$"),
                    ),
                    models.Q(
                        ("status", "entered_in_error"),
                        models.Q(
                            models.Q(
                                ("workflow_finalized_at__isnull", False),
                                ("workflow_finalized_by__isnull", False),
                                ("finalized_snapshot_hash__regex", "^[0-9a-f]{64}$"),
                            ),
                            models.Q(
                                ("workflow_finalized_at__isnull", True),
                                ("workflow_finalized_by__isnull", True),
                                ("finalized_snapshot_hash", ""),
                            ),
                            _connector="OR",
                        ),
                    ),
                    models.Q(
                        ("status", "draft"),
                        ("workflow_finalized_at__isnull", True),
                        ("workflow_finalized_by__isnull", True),
                        ("finalized_snapshot_hash", ""),
                    ),
                    _connector="OR",
                ),
                name="formsub_finalized_snapshot_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="formsubmissioncommand",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "command_type__in",
                        ["update_draft", "finalize", "amend", "enter_in_error"],
                    )
                ),
                name="formsub_cmd_type_ck",
            ),
        ),
    ]
