# Generated by Django 6.0 on 2026-07-20 17:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emr", "0092_clinical_text_resource"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="condition",
            name="client_request_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="condition",
            name="client_request_payload_hash",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="condition",
            name="clinical_domain",
            field=models.CharField(default="general", max_length=64),
        ),
        migrations.AddConstraint(
            model_name="condition",
            constraint=models.UniqueConstraint(
                condition=models.Q(("client_request_id__isnull", False)),
                fields=("client_request_id",),
                name="condition_client_request_id_uniq",
            ),
        ),
    ]
