# Generated by Django 6.0 on 2026-09-11 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emr", "0101_emergency_admission"),
        ("facility", "0484_remove_facility_discount_codes_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="consultclosure",
            name="consultclosure_snapshot_ck",
        ),
        migrations.AlterField(
            model_name="consultclosure",
            name="appointment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="emr.tokenbooking",
            ),
        ),
        migrations.AlterField(
            model_name="consultclosure",
            name="token",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="emr.token",
            ),
        ),
        migrations.AddConstraint(
            model_name="consultclosure",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("closure_number__gt", 0),
                    ("policy_version__gt", 0),
                    ("preflight_version__gt", 0),
                    ("form_source_version__gt", 0),
                    ("policy_hash__regex", "^[0-9a-f]{64}$"),
                    ("preflight_hash__regex", "^[0-9a-f]{64}$"),
                    ("form_source_hash__regex", "^[0-9a-f]{64}$"),
                    ("form_artifact_hash__regex", "^[0-9a-f]{64}$"),
                    ("closure_hash__regex", "^[0-9a-f]{64}$"),
                    ("encounter_status", "completed"),
                    models.Q(
                        models.Q(
                            ("appointment__isnull", False),
                            ("booking_status", "fulfilled"),
                            ("policy_id", "care.standard.consult-close"),
                            ("token__isnull", False),
                            ("token_status", "FULFILLED"),
                        ),
                        models.Q(
                            ("appointment__isnull", True),
                            ("booking_status", "not_required"),
                            ("policy_id", "care.standard.emergency-close"),
                            ("token__isnull", True),
                            ("token_status", "not_required"),
                        ),
                        _connector="OR",
                    ),
                    ("created_by", models.F("closed_by")),
                    ("updated_by", models.F("closed_by")),
                ),
                name="consultclosure_snapshot_ck",
            ),
        ),
    ]
